apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      name: predict
  template:
    metadata:
      labels:
        name: predict
    spec:
      hostAliases:
      - ip: "192.168.195.1"
        hostnames:
        - "k8s-alpha-master"
      - ip: "192.168.195.2"
        hostnames:
        - "k8s-alpha-node1"
      - ip: "192.168.195.3"
        hostnames:
        - "k8s-alpha-node2"
      containers:
        - name: predict
          image: registry.cn-hangzhou.aliyuncs.com/limingmax-test/predict:nocv5 
          env:
          - name: REDIS_IP
            value: "192.168.193.1"
          - name: REDIS_PORT
            value: "30098"
          - name: KAFKA_IP
            value: "192.168.195.1"
          - name: KAFKA_PORT
            value: "32400" 
          - name: HBASE_IP
            value: "192.168.195.1"
          - name: HBASE_PORT
            value: "9090"
          - name: PRODUCER_TOPIC
            value: "ai_predictor_alert"
          command: ['/bin/bash', '/service/predict/src/start.sh']


